### ISSUE TITLE
iti1480a-capture fails with LIBUSB_ERROR_INVALID_PARAM when used with upstream FX2 firmware

### ISSUE THREAD

**Issue by speachy** [vpelletier/ITI1480A-linux#5]
Traceback (most recent call last):
  File "/bin/iti1480a-capture", line 9, in <module>
    load_entry_point('ITI1480A-linux==3.0.1', 'console_scripts', 'iti1480a-capture')()
  File "build/bdist.linux-x86_64/egg/iti1480a/capture.py", line 422, in main
  File "build/bdist.linux-x86_64/egg/iti1480a/capture.py", line 304, in USBAnalyzer
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 1413, in getASCIIStringDescriptor
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 133, in mayRaiseUSBError
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 125, in raiseUSBError
usb1.USBErrorInvalidParam: LIBUSB_ERROR_INVALID_PARAM [-2]

And nothing is actually ever captured.   The link LEDs never come on, but the "host power" LED is okay.

I'm using the upstream 4.3.0 firmware release.

**Comment by speachy** [comment]
If I comment out the "Standard-Compliant" check in the USBAnalyzer() function and always return the "CompatibleUSBAnalyzer()" thing it gets a bit farther:

Traceback (most recent call last):
  File "/bin/iti1480a-capture", line 9, in <module>
    load_entry_point('ITI1480A-linux==3.0.1', 'console_scripts', 'iti1480a-capture')()
  File "build/bdist.linux-x86_64/egg/iti1480a/capture.py", line 423, in main
  File "build/bdist.linux-x86_64/egg/iti1480a/capture.py", line 56, in sendFirmware
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 1519, in bulkRead
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 1480, in _bulkTransfer
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 133, in mayRaiseUSBError
  File "build/bdist.linux-x86_64/egg/usb1/__init__.py", line 125, in raiseUSBError
usb1.USBErrorIO: LIBUSB_ERROR_IO [-1]

(Unconditionally returning the the CompliantUSBAnalyzer() path instead ends up triggering LIBUSB_ERROR_PIPE instead..)

**Comment by speachy** [comment]
Apparently, using the bundled "compliant" ITI1480A.ihx firmware works.  Maybe something changed in a recent upstream FX2 firmware builds.

**Comment by vpelletier** [comment]
Thanks for the bug report.

I fixed the probe function bug and the FIFO emptying bug, it should now work.

Probe function was reading descriptor number zero, which is invalid, and FIFO emptying must consider emptying successful when it gets errors (sadly, debugging USB protocol errors controlling a USB protocol analyser is not the easiest... as it's my only analyser. And usbmon only tell me it's -EPROTO).

Compatible (aka upstream) and Compliant (aka my own) FX2 firmwares are using incompatible protocols to control basic operations (begin of FPGA reset, firmware upload, run, pause, stop), so I do not recommend keeping your edit.

**Comment by speachy** [comment]
I finally had a chance to try this again -- The code changes you made allow the OEM firmware to boot the device up.  However, I was having problems getting a successful capture until I went back to the "compliant" firmware.  I then proceeded to slurp down several hundred megabytes of logs.  :)

Thanks for all your work on this!

**Comment by vpelletier** [comment]
Thanks for testing and reporting.

FWIW, I also have from time to time problem with either garbage at capture start (most annoying being when it is the "end of capture" marker as host software then promptly exits) or somehow host software missing the end of capture mark at capture end because of some bits being flipped (resulting in a full USB bandwidth stream flooding the end of capture file...). Sometimes the second capture after host-side plug works, sometimes it is to unplug and replug host-side. The EZ-USB firmware I wrote tries hard to flush device fifos, which is not as simple as it should be, partly because the whip spec is not always consistent with itself and its application notes.

Also, starting capture before captured link enumerates the device is required as the analyser has to react to chirps to keep track of bus speed.
